version: "3"
services:
  app:
    # image: node:16
    container_name: app
    tty: true
    build: .
    # volumes:
    #   - ./dist:/dist
    #   - ./docs:/docs
    ports:
      - 3009:3004
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: botafes
      MYSQL_USER: levelenter
      MYSQL_PASSWORD: levelenter!
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3310:3306
